mongo-cluster:
  restart: always
  environment:
    MONGO_SERVICE_NAME: mongo-cluster
  tty: true
  entrypoint: /opt/rancher/bin/entrypoint.sh
  command:
    - --replSet
    - bitbuilder
  image: mongo:3.2
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: mongo-base, mongo-datavolume
    io.rancher.scheduler.affinity:host_label: role.db=1
  volumes_from:
    - mongo-datavolume
    - mongo-base
mongo-base:
  restart: always
  tty: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label: role.db=1
  image: danielbodnar/mongodb-conf:bitbuilder
  stdin_open: true
  entrypoint: /bin/true
mongo-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label: role.db=1
  volumes:
    - /data/mongodb:/data/db
  entrypoint: /bin/true
  image: busybox
